name: symbolic_math_bridge
description: "A Flutter plugin providing a high-performance FFI bridge to the SymEngine symbolic math stack."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Add the ffi package dependency
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftSymbolicMathBridgePlugin
        # This flag is essential for FFI plugins on iOS and macOS
        ffiPlugin: true
      macos:
        pluginClass: SwiftSymbolicMathBridgePlugin
        ffiPlugin: true
